[build]
  Functions = "lambda"
  Command = "npm run lambda-build"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/json/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"